#!/usr/bin/env php
<?php

declare(strict_types=1);

require dirname(__DIR__).'/vendor/autoload.php';

use Lode\AccessSyncLendEngine\command\ConvertContactsCommand;
use Lode\AccessSyncLendEngine\command\ConvertWebsiteCsvsCommand;
use Lode\AccessSyncLendEngine\command\GatherExtraDataContactsCommand;
use Lode\AccessSyncLendEngine\command\GatherExtraDataItemsCommand;
use Lode\AccessSyncLendEngine\command\GatherExtraDataMembershipsCommand;
use Lode\AccessSyncLendEngine\command\InsightDuplicateContactsCommand;
use Lode\AccessSyncLendEngine\command\ObfuscateContactsCommand;
use Symfony\Component\Console\Application;

$application = new Application();

$application->add(new ConvertContactsCommand());
$application->add(new ConvertWebsiteCsvsCommand());
$application->add(new InsightDuplicateContactsCommand());
$application->add(new GatherExtraDataContactsCommand());
$application->add(new GatherExtraDataItemsCommand());
$application->add(new GatherExtraDataMembershipsCommand());
$application->add(new ObfuscateContactsCommand());

$application->run();
