#!/usr/bin/env php
<?php

declare(strict_types=1);

require dirname(__DIR__).'/vendor/autoload.php';

use Lode\AccessSyncLendEngine\command\ConvertWebsiteCsvsCommand;
use Symfony\Component\Console\Application;

$application = new Application();

$application->add(new ConvertWebsiteCsvsCommand());

$application->run();
