#!/usr/bin/env php
<?php

declare(strict_types=1);

require dirname(__DIR__).'/vendor/autoload.php';

use Lode\AccessSyncLendEngine\command\ConvertContactsCommand;
use Lode\AccessSyncLendEngine\command\ConvertItemsCommand;
use Lode\AccessSyncLendEngine\command\ConvertWebsiteCsvsCommand;
use Lode\AccessSyncLendEngine\command\GatherExtraDataContactNotesCommand;
use Lode\AccessSyncLendEngine\command\GatherExtraDataContactsCommand;
use Lode\AccessSyncLendEngine\command\GatherExtraDataItemCustomFieldsCommand;
use Lode\AccessSyncLendEngine\command\GatherExtraDataItemImagesCommand;
use Lode\AccessSyncLendEngine\command\GatherExtraDataItemPartsCommand;
use Lode\AccessSyncLendEngine\command\GatherExtraDataItemsCommand;
use Lode\AccessSyncLendEngine\command\GatherExtraDataMembershipsCommand;
use Lode\AccessSyncLendEngine\command\InsightCommand;
use Lode\AccessSyncLendEngine\command\ObfuscateContactsCommand;
use Symfony\Component\Console\Application;

$application = new Application();

// convert to csvs ready for importing into lend engine admin
$application->add(new ConvertContactsCommand());
$application->add(new ConvertItemsCommand());
$application->add(new ConvertWebsiteCsvsCommand());

// gather extra data for importing into lend engine as raw sql
$application->add(new GatherExtraDataContactsCommand());
$application->add(new GatherExtraDataContactNotesCommand());
$application->add(new GatherExtraDataItemsCommand());
$application->add(new GatherExtraDataItemCustomFieldsCommand());
$application->add(new GatherExtraDataItemPartsCommand());
$application->add(new GatherExtraDataMembershipsCommand());
$application->add(new GatherExtraDataItemImagesCommand());

// other tooling
$application->add(new InsightCommand());
$application->add(new ObfuscateContactsCommand());

$application->run();
